packages:
  - '.'
overrides:
  vite: 6.3.5
allowBuilds:
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
supportedArchitectures:
  os:
    - linux
    - darwin
    - current
  cpu:
    - x64
    - arm64
    - current
  libc:
    - glibc
    - current
