packages:
  - '.'
allowBuilds:
  '@tailwindcss/oxide': true
  better-sqlite3: true
  core-js: true
  esbuild: true
supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - glibc
