// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface FeaturedCase {
  slug: string;
  title: string;
  subtitle: string;
  imagePosition: "left" | "right";
  stats: string[];
  image: string;
}

export interface GridCase {
  slug: string;
  title: string;
  subtitle: string;
  image: string;
}

export const featuredCases: FeaturedCase[] = [
  {
    "slug": "tap2link",
    "title": "Tap2Link – more than a digital business card.",
    "subtitle": "A digital service portal for complex B2B processes in just 8 weeks.",
    "imagePosition": "right",
    "stats": [
      "+230% user interaction",
      "Launched in 16 weeks",
      "95% customer satisfaction"
    ],
    "image": "/uploads/cases/tap2link-card.png"
  },
  {
    "slug": "brylliant",
    "title": "Brylliant – the tool for perfect briefings",
    "subtitle": "A scalable tool for efficient briefings, clean processes, and strategic clarity.",
    "imagePosition": "left",
    "stats": [
      "Structured templates & guided briefings",
      "2x faster briefing approvals",
      "95% fewer follow-up questions from agencies"
    ],
    "image": "/uploads/cases/brylliant-card.png"
  },
  {
    "slug": "moerschen",
    "title": "Moerschen – website relaunch for better communication",
    "subtitle": "A digital service portal for complex B2B processes in just 8 weeks.",
    "imagePosition": "right",
    "stats": [
      "45% more contact inquiries via the website",
      "Users find the right contact 2× faster than before",
      "8 weeks from kickoff to launch"
    ],
    "image": "/uploads/cases/moerschen-card.png"
  },
  {
    "slug": "machinemaster",
    "title": "MachineMaster – agricultural machinery sales platform",
    "subtitle": "A digital sales tool for dealers, sales, and field reps — to MVP in just 12 weeks",
    "imagePosition": "left",
    "stats": [
      "+230% user interaction",
      "10% sales increase",
      "5/5 star reviews"
    ],
    "image": "/uploads/cases/machinemaster-card.png"
  }
];

export const gridCases: GridCase[] = [
  {
    "slug": "neuer-look",
    "title": "New look, new website",
    "subtitle": "A digital service portal for complex B2B processes in just 8 weeks.",
    "image": "/uploads/cases/neuer-look-card.png"
  },
  {
    "slug": "animation",
    "title": "Animation for more sustainability",
    "subtitle": "A digital service portal for complex B2B processes in just 8 weeks.",
    "image": "/uploads/cases/animation-card.png"
  },
  {
    "slug": "scanservice",
    "title": "Your ScanService",
    "subtitle": "A digital service portal for complex B2B processes in just 8 weeks.",
    "image": "/uploads/cases/scanservice-card.png"
  }
];
