// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface StrengthFeature {
  icon: string;
  title: string;
  subtitle: string;
}

export interface CoreService {
  key: "check" | "build" | "care";
  step: string;
  label: string;
  title: string;
  tagline: string;
  meta: string;
  description: string;
  input: string;
  output: string;
  bullets: string[];
  ctaLabel: string;
}

export interface LeistungenData {
  heroEyebrow: string;
  heroTitlePrefix: string;
  heroTitleHighlight: string;
  heroSubheading: string;
  coreHeading: string;
  coreIntro: string;
  coreServices: CoreService[];
  skillsHeading: string;
  skillsIntro: string;
  skillStepLabels: Record<"check" | "build" | "care", string>;
  ctaHeading: string;
  ctaBody: string;
  contactCallout: string;
  strengthHeadline: string;
  strengthDescription: string;
  strengthFeatures: StrengthFeature[];
}

export const leistungenData: LeistungenData = {
  heroEyebrow: "Services",
  heroTitlePrefix: "Three steps.",
  heroTitleHighlight: "One pulse.",
  heroSubheading: "First find out what is really going on. Then build what makes the biggest difference. Then stay with it. Everything else is detail.",
  coreHeading: "Check. Build. Care.",
  coreIntro: "Each step builds on the one before. After each, you decide whether to continue — no obligation to take the next one.",
  coreServices: [
  {
    "key": "check",
    "step": "01",
    "label": "Understand",
    "title": "Pulse Check",
    "tagline": "Where is the biggest lever?",
    "meta": "1–2 days",
    "description": "We look at how your company actually works: processes, data, tools, team. What you get at the end is not a presentation but a sorted list.",
    "input": "Your processes, data and tools — the way they really are today.",
    "output": "A prioritised roadmap with the use cases worth doing first.",
    "bullets": [
      "An AI opportunity map instead of buzzword bingo",
      "3–5 use cases, ranked by impact",
      "No 40-page report nobody reads"
    ],
    "ctaLabel": "Take the Pulse Check"
  },
  {
    "key": "build",
    "step": "02",
    "label": "Build",
    "title": "Pulse Build",
    "tagline": "From plan to running solution.",
    "meta": "from 4 weeks",
    "description": "We implement the use cases that matter most — in weeks, not quarters. Fixed scope, dedicated people, a real production system instead of a prototype for the drawer.",
    "input": "The prioritised use case from your Pulse Check.",
    "output": "A solution that runs in your team’s daily work.",
    "bullets": [
      "Fixed scope, one dedicated contact",
      "Live in production, not in demo mode",
      "Handover included — your team can work with it"
    ],
    "ctaLabel": "Talk about a build"
  },
  {
    "key": "care",
    "step": "03",
    "label": "Keep going",
    "title": "Pulse Care",
    "tagline": "A system that keeps growing.",
    "meta": "ongoing",
    "description": "Living software needs care — with AI even more so. We stay on board: fixed sessions, continuous monitoring, regular evolution.",
    "input": "The solution that is running.",
    "output": "A system that grows with your business instead of ageing out.",
    "bullets": [
      "Fixed sessions every month",
      "Monitoring and dashboard",
      "Annual Pulse Check refresh"
    ],
    "ctaLabel": "Discuss ongoing care"
  }
],
  skillsHeading: "Four skills. Depending on what your case needs.",
  skillsIntro: "The three steps are the how. This is the with-what — four disciplines we bring to bear differently in every step.",
  skillStepLabels: {
  "check": "Check",
  "build": "Build",
  "care": "Care"
},
  ctaHeading: "Not sure where you stand?",
  ctaBody: "The Pulse Check takes five minutes and costs nothing. Afterwards you will know more than after the next strategy workshop.",
  contactCallout: "Looking for honest advice instead of buzzwords? Call or email us — we listen before we build.",
  strengthHeadline: "Our strength:\nDigital product development",
  strengthDescription: "We support you from first vision to execution — with an interdisciplinary team of strategy, design, and technology experts. Our goal: products that are technically robust, aesthetically compelling, and relevant to users. We work agile and user-centered, using the most modern tools — from no-code to AI — to reach results faster.",
  strengthFeatures: [
  {
    "icon": "users",
    "title": "User-centered conception",
    "subtitle": "Understanding what users really need"
  },
  {
    "icon": "layers",
    "title": "Scalable architecture",
    "subtitle": "Technology that grows with your business"
  },
  {
    "icon": "zap",
    "title": "Rapid prototyping & testing",
    "subtitle": "Validate and iterate on ideas early"
  },
  {
    "icon": "handshake",
    "title": "Close collaboration & transparency",
    "subtitle": "You're part of the development process"
  }
],
};
