// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface PricingPlan {
  slug: string;
  title: string;
  price: string;
  priceUnit: string;
  badge: string;
  badgeColor: string;
  description: string;
  cta: string;
  features: string[];
}

export const pricingPlans: PricingPlan[] = [
  {
    "slug": "erstgespraech",
    "title": "Free intro call",
    "price": "€0",
    "priceUnit": "",
    "badge": "Quick start",
    "badgeColor": "#FBBA10",
    "description": "Ideal for teams who have an idea or want to solve a problem. We spend an hour with you, listen, think along — and give you first ideas for implementation.",
    "cta": "Book a slot",
    "features": [
      "Senior designer",
      "Miro board with stickies",
      "Project manager",
      "Your ideas stay yours"
    ]
  },
  {
    "slug": "workshop",
    "title": "Workshop with our team",
    "price": "€3,000",
    "priceUnit": "/month",
    "badge": "Quick start +",
    "badgeColor": "#2448D9",
    "description": "Together with product leads and design thinkers, we analyze your project and develop concrete, actionable ideas — visual, strategic, and realistic.",
    "cta": "Book a workshop",
    "features": [
      "2 senior designers",
      "Figma prototype",
      "Product strategist",
      "All deliverables stay yours"
    ]
  },
  {
    "slug": "entwicklung",
    "title": "App development",
    "price": "€25,000",
    "priceUnit": "/project",
    "badge": "Full package",
    "badgeColor": "#A318F8",
    "description": "From idea to live product: we build your digital product — with clear milestones, a dedicated team, and full transparency on time & budget.",
    "cta": "Start project",
    "features": [
      "Full-stack development team",
      "UX/UI design included",
      "Dedicated project manager",
      "4–16 weeks to launch",
      "Source code & IP belong to you"
    ]
  }
];
