// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
}

export const serviceDetails: ServiceDetail[] = [
  {
    "slug": "development",
    "heroHeadline": "From idea to market-ready digital product",
    "heroSubline": "We build digital products that users love and that move your business forward.",
    "heroImage": "/uploads/services/development-hero.png",
    "tags": [
      "Fastest launch",
      "Revenue-focused",
      "Rapid product iteration & market validation",
      "Close collaboration"
    ],
    "process": [
      {
        "number": "01",
        "title": "Discovery & Research",
        "description": "We get to know your business, your users, and your market. Workshop-driven, fast, and focused — so we build the right thing."
      },
      {
        "number": "02",
        "title": "Ideation & Wireframing",
        "description": "Ideas get structured, flows get sketched, and the product architecture is defined. A clear plan before a single line of code is written."
      },
      {
        "number": "03",
        "title": "Prototyping & Validation",
        "description": "We test clickable prototypes with real users before we build — reducing risk and saving development time."
      },
      {
        "number": "04",
        "title": "Design & Development",
        "description": "Pixel-perfect UI meets clean code. Our full-stack team builds fast, iteratively, and with full transparency."
      },
      {
        "number": "05",
        "title": "Launch & Scale",
        "description": "Deployment, monitoring, analytics — and continuous improvement after launch. We stay with you."
      }
    ],
    "caseTitle": "Tap2Link",
    "caseSlug": "tap2link",
    "caseSubtitle": "Tap2Link: more than a digital business card.",
    "caseImage": "/uploads/services/development-case.png",
    "caseStats": [
      {
        "value": "+35%",
        "label": "Faster onboarding process"
      },
      {
        "value": "-20%",
        "label": "Reduced support effort"
      },
      {
        "value": "+40%",
        "label": "More user interactions"
      }
    ],
    "caseDescription": "A digital service portal for complex B2B processes — from idea to launch in just 8 weeks.",
    "ctaHeadline": "Ready to build your product?",
    "ctaBody": "Let's find out in a free intro call how we can turn your idea into a market-ready product."
  },
  {
    "slug": "company-building",
    "heroHeadline": "From idea to working company",
    "heroSubline": "We help teams develop, validate, and turn new business models into market-ready products.",
    "heroImage": "/uploads/services/company-building-hero.png",
    "tags": [
      "MVP in 12 weeks",
      "Business model design",
      "Go-to-market",
      "Team building"
    ],
    "process": [
      {
        "number": "01",
        "title": "Idea & Vision",
        "description": "We help you sharpen your idea: What's the real problem? Who's the target audience? What makes you unique?"
      },
      {
        "number": "02",
        "title": "Business Model Design",
        "description": "Lean canvas, value proposition, and revenue model — we build a viable business model based on real market data."
      },
      {
        "number": "03",
        "title": "MVP Strategy & Scope",
        "description": "What's the smallest possible product you can validate? We define the MVP scope and prioritize ruthlessly."
      },
      {
        "number": "04",
        "title": "Build & Launch",
        "description": "Our team builds the MVP — design, development, messaging. Your product goes live in 8–16 weeks."
      },
      {
        "number": "05",
        "title": "Traction & Scale",
        "description": "First users, first feedback, first revenue. We support the early growth phase and help you build your own team."
      }
    ],
    "caseTitle": "Moerschen",
    "caseSlug": "moerschen",
    "caseSubtitle": "Moerschen: from relaunch to lead machine.",
    "caseImage": "/uploads/services/company-building-case.png",
    "caseStats": [
      {
        "value": "+45%",
        "label": "More contact inquiries"
      },
      {
        "value": "8 wks",
        "label": "From kickoff to launch"
      },
      {
        "value": "2×",
        "label": "Faster to find the right contact"
      }
    ],
    "caseDescription": "Website relaunch with clear user guidance and a new communication strategy — live in 8 weeks.",
    "ctaHeadline": "Your startup. Our experience.",
    "ctaBody": "Let's find out together how to turn your business model into reality, quickly and safely."
  },
  {
    "slug": "webdesign",
    "heroHeadline": "Design that converts and delights",
    "heroSubline": "From the first sketch to a live interface — we design digital products that users truly understand.",
    "heroImage": "/uploads/services/webdesign-hero.png",
    "tags": [
      "UX research",
      "Pixel-perfect UI",
      "Design systems",
      "Mobile-first"
    ],
    "process": [
      {
        "number": "01",
        "title": "UX Research & Analysis",
        "description": "User interviews, competitive analysis, and heuristic evaluation lay the foundation for sound design decisions."
      },
      {
        "number": "02",
        "title": "User Flows & Architecture",
        "description": "Information architecture and user flows ensure users always know where they are and what comes next."
      },
      {
        "number": "03",
        "title": "Wireframes & Concept",
        "description": "Lo-fi wireframes reveal the structure before we go into detail. Fast feedback, fast iteration."
      },
      {
        "number": "04",
        "title": "Visual Design & Prototyping",
        "description": "High-fidelity UI design in Figma, including a design system and a clickable prototype for user testing."
      },
      {
        "number": "05",
        "title": "Design Handoff & Support",
        "description": "Pixel-perfect handoff to the dev team with complete documentation and dev-mode annotations."
      }
    ],
    "caseTitle": "Brylliant",
    "caseSlug": "brylliant",
    "caseSubtitle": "Brylliant: the tool for perfect briefings.",
    "caseImage": "/uploads/services/webdesign-case.png",
    "caseStats": [
      {
        "value": "2×",
        "label": "Faster briefing approvals"
      },
      {
        "value": "95%",
        "label": "Fewer follow-up questions"
      },
      {
        "value": "+60%",
        "label": "Higher user satisfaction"
      }
    ],
    "caseDescription": "A scalable tool for efficient briefings, clean processes, and strategic clarity — designed in 6 weeks.",
    "ctaHeadline": "Design that actually works.",
    "ctaBody": "Let us show you how thoughtful UX/UI design boosts your conversion rate and user satisfaction."
  },
  {
    "slug": "ki-strategie",
    "heroHeadline": "Recognize AI potential and use it consistently",
    "heroSubline": "We help you find and integrate the right AI tools — and extract real business value from them.",
    "heroImage": "/uploads/services/ki-strategie-hero.png",
    "tags": [
      "OpenAI & Gemini",
      "Workflow automation",
      "Custom AI agents",
      "Fast implementation"
    ],
    "process": [
      {
        "number": "01",
        "title": "AI Readiness Assessment",
        "description": "Analysis of your current processes, data landscape, and tech stack — to find where AI has the biggest leverage."
      },
      {
        "number": "02",
        "title": "Use Case Identification",
        "description": "Together we prioritize the AI use cases with the best ROI: automations, agents, or generative tools."
      },
      {
        "number": "03",
        "title": "Prototyping & Proof of Concept",
        "description": "Show what's possible, fast. We build a working prototype in 2–4 weeks — so you see real value."
      },
      {
        "number": "04",
        "title": "Integration & Rollout",
        "description": "From idea to production: OpenAI, Claude, Zapier, Make, n8n — we integrate AI seamlessly into your existing stack."
      },
      {
        "number": "05",
        "title": "Monitoring & Optimization",
        "description": "AI isn't a one-off project. We support ongoing operations, measure outputs, and continuously optimize."
      }
    ],
    "caseTitle": "MachineMaster",
    "caseSlug": "machinemaster",
    "caseSubtitle": "MachineMaster: AI in agricultural machinery sales.",
    "caseImage": "/uploads/services/ki-strategie-case.png",
    "caseStats": [
      {
        "value": "+230%",
        "label": "More user interactions"
      },
      {
        "value": "+10%",
        "label": "Sales increase"
      },
      {
        "value": "5/5",
        "label": "Customer ratings"
      }
    ],
    "caseDescription": "An AI-powered sales tool for dealers and field reps — from MVP in just 12 weeks.",
    "ctaHeadline": "AI in practice, not theory.",
    "ctaBody": "In a free intro call we'll show you which AI measures will make an immediate impact on your business."
  }
];
