// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface Service {
  slug: string;
  title: string;
  description: string;
  gradient: string;
  icon: "code" | "grid" | "palette" | "bot";
  tags: string[];
}

export const services: Service[] = [
  {
    "slug": "ai-automation",
    "title": "AI Automation",
    "description": "Rethinking existing processes: we turn manual business processes into intelligent, integrated workflows.",
    "gradient": "linear-gradient(-56.458deg, rgba(253, 167, 0, 0.8) 0%, rgba(253, 167, 0, 0) 100%)",
    "icon": "bot",
    "tags": [
      "AI agents & intelligent workflows",
      "Email & document process automation",
      "Knowledge & research systems",
      "Sales, service & operations automation",
      "Integration with ERP, CRM, DMS & existing tools",
      "Operation & continuous improvement"
    ]
  },
  {
    "slug": "ai-products",
    "title": "AI Products",
    "description": "Building new digital products: we develop products that don't bolt on AI as an afterthought, but design it in from day one.",
    "gradient": "linear-gradient(146.383deg, rgba(163, 24, 248, 0.8) 0%, rgba(163, 24, 248, 0) 100%)",
    "icon": "code",
    "tags": [
      "Product strategy & concept",
      "AI-native product development",
      "Prototyping & MVPs",
      "Web apps & business software",
      "AI architecture & integrations",
      "Launch & continuous development"
    ]
  },
  {
    "slug": "ai-experience",
    "title": "AI Experience",
    "description": "Designing how people and AI work together: we design interfaces, workflows, and interactions for a new generation of digital products.",
    "gradient": "linear-gradient(44.336deg, rgba(43, 149, 246, 0.8) 0%, rgba(43, 149, 246, 0) 100%)",
    "icon": "palette",
    "tags": [
      "AI interaction design",
      "Agent UX & conversational interfaces",
      "UX for complex B2B processes",
      "Product design & prototyping",
      "Design systems",
      "Evaluation & optimization"
    ]
  },
  {
    "slug": "venture-building",
    "title": "Venture Building",
    "description": "Turning opportunities into new businesses: we validate business models and build them into working digital ventures.",
    "gradient": "linear-gradient(268.344deg, rgba(255, 0, 0, 0.8) 0%, rgba(255, 0, 0, 0) 100%)",
    "icon": "grid",
    "tags": [
      "Opportunity discovery",
      "Business model & strategy",
      "Market & concept validation",
      "MVP & product development",
      "AI-native products",
      "Launch & growth"
    ]
  }
];
