// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
}

export const serviceDetails: ServiceDetail[] = [
  {
    "slug": "development",
    "heroHeadline": "From digital product to self-learning system",
    "heroSubline": "We come from software development — and use that foundation to build products that evolve with AI instead of stagnating.",
    "heroImage": "/uploads/services/development-hero.png",
    "tags": [
      "Consulting: experienced developer team, honest & human",
      "Execution: AI-driven development & automation",
      "Self-learning features instead of static software",
      "Launch-ready in 4–16 weeks"
    ],
    "process": [
      {
        "number": "01",
        "title": "Discovery & Strategy",
        "description": "We listen and get to know your business in direct conversation, not through a questionnaire. Honest advice from people who have built things themselves."
      },
      {
        "number": "02",
        "title": "Architecture & AI Concept",
        "description": "Together we decide where classic software is enough — and where a self-learning system or an AI agent makes the difference."
      },
      {
        "number": "03",
        "title": "AI-Assisted Prototyping",
        "description": "Our developers use AI tools to build prototypes in days instead of weeks — validated with real users."
      },
      {
        "number": "04",
        "title": "Development & Automation",
        "description": "Where code used to be written line by line, AI agents now take over recurring tasks — we build the tools that build new tools."
      },
      {
        "number": "05",
        "title": "Launch & Continuous Learning",
        "description": "Development doesn't stop at launch: the system keeps learning from real data and is optimized automatically."
      }
    ],
    "caseTitle": "Tap2Link",
    "caseSlug": "tap2link",
    "caseSubtitle": "Tap2Link: more than a digital business card.",
    "caseImage": "/uploads/services/development-case.png",
    "caseStats": [
      {
        "value": "+35%",
        "label": "Faster onboarding process"
      },
      {
        "value": "-20%",
        "label": "Reduced support effort"
      },
      {
        "value": "+40%",
        "label": "More user interactions"
      }
    ],
    "caseDescription": "A digital service portal for complex B2B processes — from idea to launch in just 8 weeks.",
    "ctaHeadline": "Ready for a product that thinks along?",
    "ctaBody": "Let's find out in an honest intro call whether your next product needs classic software or a self-learning system."
  },
  {
    "slug": "company-building",
    "heroHeadline": "From idea to AI-powered company",
    "heroSubline": "Business-model consulting stays a matter of trust between people. For execution, we rely on AI to get your MVP live faster and leaner.",
    "heroImage": "/uploads/services/company-building-hero.png",
    "tags": [
      "Business-model consulting from experienced founders",
      "MVP execution with AI-driven development",
      "Automated processes instead of manual busywork",
      "MVP live in 8–16 weeks"
    ],
    "process": [
      {
        "number": "01",
        "title": "Idea & Vision",
        "description": "In a personal conversation, we sharpen your idea: the real problem, the real audience, the real USP."
      },
      {
        "number": "02",
        "title": "Business Model Consulting",
        "description": "Lean canvas and revenue model take shape in dialogue with our team — not an automated template, but real entrepreneurial experience."
      },
      {
        "number": "03",
        "title": "AI-Focused MVP Scope",
        "description": "We define which processes your company can automate and scale with AI agents from day one."
      },
      {
        "number": "04",
        "title": "Build & Automation",
        "description": "Our team builds your MVP — design, development, messaging. AI takes over what repeats, so you can focus on growth."
      },
      {
        "number": "05",
        "title": "Traction & Scale",
        "description": "We support the first users, the first feedback, the first revenue — and help embed AI-driven processes in your own team."
      }
    ],
    "caseTitle": "Moerschen",
    "caseSlug": "moerschen",
    "caseSubtitle": "Moerschen: from relaunch to lead machine.",
    "caseImage": "/uploads/services/company-building-case.png",
    "caseStats": [
      {
        "value": "+45%",
        "label": "More contact inquiries"
      },
      {
        "value": "8 wks",
        "label": "From kickoff to launch"
      },
      {
        "value": "2×",
        "label": "Faster to find the right contact"
      }
    ],
    "caseDescription": "Website relaunch with clear user guidance and a new communication strategy — live in 8 weeks.",
    "ctaHeadline": "Your startup. Our experience. AI as an accelerator.",
    "ctaBody": "Let's find out in a free intro call how we turn your business model into reality with real experience and smart automation."
  },
  {
    "slug": "webdesign",
    "heroHeadline": "Design that learns alongside your users",
    "heroSubline": "Good UX starts with real listening — that stays handmade. For execution and personalization, we use AI so your interface keeps evolving.",
    "heroImage": "/uploads/services/webdesign-hero.png",
    "tags": [
      "UX consulting in direct conversation with our team",
      "AI-powered design systems & content creation",
      "Personalized interfaces instead of static screens",
      "From sketch to live interface in 4–8 weeks"
    ],
    "process": [
      {
        "number": "01",
        "title": "UX Research & Analysis",
        "description": "User interviews and competitive analysis — led by real people who listen, not by a survey tool."
      },
      {
        "number": "02",
        "title": "Information Architecture",
        "description": "Together we define how users find their way — the foundation for any good interface, classic or AI-powered."
      },
      {
        "number": "03",
        "title": "AI-Assisted Concept",
        "description": "Our designers use AI tools for faster wireframes and variants — the decision still rests with a human."
      },
      {
        "number": "04",
        "title": "Visual Design & Design System",
        "description": "A design system that grows with AI-powered components instead of starting from zero with every new feature."
      },
      {
        "number": "05",
        "title": "Handoff & Learning Optimization",
        "description": "After launch, we measure how users actually use the interface — and keep optimizing based on real data."
      }
    ],
    "caseTitle": "Brylliant",
    "caseSlug": "brylliant",
    "caseSubtitle": "Brylliant: the tool for perfect briefings.",
    "caseImage": "/uploads/services/webdesign-case.png",
    "caseStats": [
      {
        "value": "2×",
        "label": "Faster briefing approvals"
      },
      {
        "value": "95%",
        "label": "Fewer follow-up questions"
      },
      {
        "value": "+60%",
        "label": "Higher user satisfaction"
      }
    ],
    "caseDescription": "A scalable tool for efficient briefings, clean processes, and strategic clarity — designed in 6 weeks.",
    "ctaHeadline": "Design that doesn't stand still.",
    "ctaBody": "Let us show you in an honest intro call how thoughtful UX design and smart AI tools achieve more together."
  },
  {
    "slug": "ki-strategie",
    "heroHeadline": "We build the tools that build new tools",
    "heroSubline": "As a software team, we know the pitfalls of AI projects firsthand. We handle consulting in person; self-learning systems and AI agents handle the automation.",
    "heroImage": "/uploads/services/ki-strategie-hero.png",
    "tags": [
      "AI readiness consulting with an experienced software team",
      "Custom AI agents & self-learning workflows",
      "Deep automation instead of isolated tools",
      "First prototype in 2–4 weeks"
    ],
    "process": [
      {
        "number": "01",
        "title": "AI Readiness Assessment",
        "description": "We take an honest look at where your company stands — processes, data, tech stack. No buzzword analysis, just a real conversation."
      },
      {
        "number": "02",
        "title": "Use Case Prioritization",
        "description": "Together we decide which processes are genuinely suited for AI agents — and which aren't, yet."
      },
      {
        "number": "03",
        "title": "Prototyping Self-Learning Systems",
        "description": "We build a working agent or automation workflow in 2–4 weeks that learns from real data."
      },
      {
        "number": "04",
        "title": "Integration & Rollout",
        "description": "From idea to production: we integrate AI agents so they automate your existing stack rather than replace it."
      },
      {
        "number": "05",
        "title": "Monitoring & Evolution",
        "description": "Self-learning systems are never 'finished'. We support ongoing operations, measure results, and let the systems keep learning."
      }
    ],
    "caseTitle": "MachineMaster",
    "caseSlug": "machinemaster",
    "caseSubtitle": "MachineMaster: AI in agricultural machinery sales.",
    "caseImage": "/uploads/services/ki-strategie-case.png",
    "caseStats": [
      {
        "value": "+230%",
        "label": "More user interactions"
      },
      {
        "value": "+10%",
        "label": "Sales increase"
      },
      {
        "value": "5/5",
        "label": "Customer ratings"
      }
    ],
    "caseDescription": "An AI-powered sales tool for dealers and field reps — from MVP in just 12 weeks.",
    "ctaHeadline": "AI that actually automates — not just a chatbot.",
    "ctaBody": "In a free intro call with our team, we'll talk honestly about where AI agents can already make a difference in your business today."
  }
];
