// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export const siteData = {
  heroHeadline: "We build digital products for your business.",
  heroSubline: "A small, focused team of strategy, design, and project management experts ships digital products that actually work — in just a few weeks.",
  heroCta: "Book a call",
  heroCtaSecondary: "View projects",
  clientLogosLabel: "Trusted by these clients",
};
