// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export const siteData = {
  heroHeadline: "We build what's next.",
  heroSubline: "We help businesses find, build and scale what AI makes possible.",
  heroCta: "Take the AI Pulse Check now",
  heroCtaSecondary: "Contact",
  clientLogosLabel: "Trusted by these clients",
};
