/**
 * Build step: reads content/**\/*.md and writes src/data/{de,en}/*.ts in the
 * exact shapes the components already consume, split per locale via each
 * document's `language` field.
 *
 * All content lives in YAML frontmatter (there are no markdown bodies), so
 * reading it is a plain file read + YAML parse.
 */
import { writeFileSync, mkdirSync, readFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(__dirname, "../src/data");
const contentDir = resolve(__dirname, "../content");

const LOCALES = ["de", "en"] as const;
type Locale = (typeof LOCALES)[number];

const siteRelativePath: Record<Locale, string> = {
  de: "site/home.md",
  en: "site/home.en.md",
};

const leistungenRelativePath: Record<Locale, string> = {
  de: "site/leistungen.md",
  en: "site/leistungen.en.md",
};

const aboutRelativePath: Record<Locale, string> = {
  de: "about/about.md",
  en: "about/about.en.md",
};

/** Frontmatter of a single document, addressed relative to content/. */
function readDoc(relPath: string): any {
  return matter(readFileSync(resolve(contentDir, relPath), "utf-8")).data;
}

/**
 * Frontmatter of every .md in a content/ subdirectory, narrowed to one locale
 * and ordered by the `order` field the editors control.
 */
function readCollection(dir: string, locale: Locale): any[] {
  const abs = resolve(contentDir, dir);
  return readdirSync(abs)
    .filter((f) => f.endsWith(".md"))
    .map((f) => matter(readFileSync(resolve(abs, f), "utf-8")).data)
    .filter((d) => (d.language ?? "de") === locale)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

function banner() {
  return "// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.\n";
}

function strLit(s: string) {
  return JSON.stringify(s ?? "");
}

async function generateLocale(locale: Locale) {
  const outDir = resolve(dataDir, locale);
  mkdirSync(outDir, { recursive: true });

  const site = readDoc(siteRelativePath[locale]);
  const about = readDoc(aboutRelativePath[locale]);
  const leistungen = readDoc(leistungenRelativePath[locale]);
  const services = readCollection("services", locale);
  const cases = readCollection("cases", locale);
  const blogPosts = readCollection("blog", locale);

  /* ── site.ts ─────────────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "site.ts"),
    `${banner()}
export const siteData = {
  heroHeadline: ${strLit(site.heroHeadline)},
  heroSubline: ${strLit(site.heroSubline)},
  heroCta: ${strLit(site.heroCta)},
  heroCtaSecondary: ${strLit(site.heroCtaSecondary)},
  clientLogosLabel: ${strLit(site.clientLogosLabel)},
};
`
  );

  /* ── about.ts ────────────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "about.ts"),
    `${banner()}
export interface ValueItem {
  title: string;
  description: string;
}

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface AboutData {
  heroTitle: string;
  heroSubheading: string;
  missionTitle: string;
  missionText: string;
  valuesTitle: string;
  valuesItems: ValueItem[];
  processTitle: string;
  processSteps: ProcessStep[];
  teamTitle: string;
  teamDescription: string;
  cta: string;
}

export const aboutData: AboutData = {
  heroTitle: ${strLit(about.heroTitle)},
  heroSubheading: ${strLit(about.heroSubheading)},
  missionTitle: ${strLit(about.missionTitle)},
  missionText: ${strLit(about.missionText)},
  valuesTitle: ${strLit(about.valuesTitle)},
  valuesItems: ${JSON.stringify(
    (about.valuesItems ?? []).map((v) => ({
      title: v!.title,
      description: v!.description,
    })),
    null,
    2
  )},
  processTitle: ${strLit(about.processTitle)},
  processSteps: ${JSON.stringify(
    (about.processSteps ?? []).map((p) => ({
      number: p!.number,
      title: p!.title,
      description: p!.description,
    })),
    null,
    2
  )},
  teamTitle: ${strLit(about.teamTitle)},
  teamDescription: ${strLit(about.teamDescription)},
  cta: ${strLit(about.cta)},
};
`
  );

  /* ── services.ts ─────────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "services.ts"),
    `${banner()}
export interface Service {
  slug: string;
  title: string;
  description: string;
  gradient: string;
  icon: "code" | "grid" | "palette" | "bot";
  tags: string[];
}

export const services: Service[] = ${JSON.stringify(
      services.map((s) => ({
        slug: s.slug,
        title: s.title,
        description: s.description,
        gradient: s.gradient,
        icon: s.icon,
        tags: s.tags ?? [],
      })),
      null,
      2
    )};
`
  );

  /* ── serviceDetails.ts ────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "serviceDetails.ts"),
    `${banner()}
export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
}

export const serviceDetails: ServiceDetail[] = ${JSON.stringify(
      services.map((s) => ({
        slug: s.slug,
        heroHeadline: s.heroHeadline,
        heroSubline: s.heroSubline,
        heroImage: s.heroImage,
        tags: s.tags ?? [],
        process: (s.process ?? []).map((p) => ({
          number: p!.number,
          title: p!.title,
          description: p!.description,
        })),
        caseTitle: s.caseTitle,
        caseSlug: s.caseSlug,
        caseSubtitle: s.caseSubtitle,
        caseImage: s.caseImage,
        caseStats: (s.caseStats ?? []).map((c) => ({
          value: c!.value,
          label: c!.label,
        })),
        caseDescription: s.caseDescription,
        ctaHeadline: s.ctaHeadline,
        ctaBody: s.ctaBody,
      })),
      null,
      2
    )};
`
  );

  /* ── cases.ts ─────────────────────────────────────────────────────────── */
  const featured = cases.filter((c) => c.featured);
  const grid = cases.filter((c) => !c.featured);

  writeFileSync(
    resolve(outDir, "cases.ts"),
    `${banner()}
export interface FeaturedCase {
  slug: string;
  title: string;
  subtitle: string;
  imagePosition: "left" | "right";
  stats: string[];
  image: string;
}

export interface GridCase {
  slug: string;
  title: string;
  subtitle: string;
  image: string;
}

export const featuredCases: FeaturedCase[] = ${JSON.stringify(
      featured.map((c) => ({
        slug: c.slug,
        title: c.title,
        subtitle: c.subtitle,
        imagePosition: c.imagePosition ?? "left",
        stats: c.stats ?? [],
        image: c.image,
      })),
      null,
      2
    )};

export const gridCases: GridCase[] = ${JSON.stringify(
      grid.map((c) => ({
        slug: c.slug,
        title: c.title,
        subtitle: c.subtitle,
        image: c.image,
      })),
      null,
      2
    )};
`
  );

  /* ── caseDetails.ts ───────────────────────────────────────────────────── */
  const withDetail = cases.filter((c) => c.heroHeadline && c.description);

  writeFileSync(
    resolve(outDir, "caseDetails.ts"),
    `${banner()}
export interface CaseDetail {
  slug: string;
  category: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  description: string;
  background: string;
  problem: string;
  solution: string;
  stats: {
    value: string;
    label: string;
  }[];
  mockupImages: string[];
}

export const caseDetailsMap: Record<string, CaseDetail> = ${JSON.stringify(
      Object.fromEntries(
        withDetail.map((c) => [
          c.slug,
          {
            slug: c.slug,
            category: c.category,
            heroHeadline: c.heroHeadline,
            heroSubline: c.heroSubline,
            heroImage: c.heroImage,
            description: c.description,
            background: c.background,
            problem: c.problem,
            solution: c.solution,
            stats: (c.detailStats ?? []).map((s) => ({
              value: s!.value,
              label: s!.label,
            })),
            mockupImages: c.mockupImages ?? [],
          },
        ])
      ),
      null,
      2
    )};

export function getCaseDetail(slug: string): CaseDetail | undefined {
  return caseDetailsMap[slug];
}
`
  );


  /* ── blog.ts ─────────────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "blog.ts"),
    `${banner()}
export interface BlogContentBlock {
  type: "heading" | "paragraph";
  text: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  topicSlug: "development" | "company-building" | "ui-ux" | "ai-consulting";
  topic: string;
  readTime: string;
  featured: boolean;
  publishedDate: string;
  author: string;
  content: BlogContentBlock[];
}

export const blogPosts: BlogPost[] = ${JSON.stringify(
      blogPosts.map((p) => ({
        slug: p.slug,
        title: p.title,
        excerpt: p.excerpt,
        topicSlug: p.topicSlug,
        topic: p.topic,
        readTime: p.readTime,
        featured: !!p.featured,
        publishedDate: p.publishedDate,
        author: p.author,
        content: (p.content ?? []).map((b: any) => ({
          type: b!.type,
          text: b!.text,
        })),
      })),
      null,
      2
    )};
`
  );

  /* ── leistungen.ts ───────────────────────────────────────────────────── */
  writeFileSync(
    resolve(outDir, "leistungen.ts"),
    `${banner()}
export interface StrengthFeature {
  icon: string;
  title: string;
  subtitle: string;
}

export interface LeistungenData {
  heroTitlePrefix: string;
  heroTitleHighlight: string;
  heroSubheading: string;
  contactCallout: string;
  strengthHeadline: string;
  strengthDescription: string;
  strengthFeatures: StrengthFeature[];
}

export const leistungenData: LeistungenData = {
  heroTitlePrefix: ${strLit(leistungen.heroTitlePrefix)},
  heroTitleHighlight: ${strLit(leistungen.heroTitleHighlight)},
  heroSubheading: ${strLit(leistungen.heroSubheading)},
  contactCallout: ${strLit(leistungen.contactCallout)},
  strengthHeadline: ${strLit(leistungen.strengthHeadline)},
  strengthDescription: ${strLit(leistungen.strengthDescription)},
  strengthFeatures: ${JSON.stringify(
    (leistungen.strengthFeatures ?? []).map((f: any) => ({
      icon: f.icon,
      title: f.title,
      subtitle: f.subtitle,
    })),
    null,
    2
  )},
};
`
  );

  console.log(
    `generate-content[${locale}]: wrote site.ts, about.ts, leistungen.ts, services.ts, serviceDetails.ts, cases.ts (${featured.length} featured / ${grid.length} grid), caseDetails.ts (${withDetail.length} with detail), blog.ts (${blogPosts.length} posts)`
  );
}

async function main() {
  for (const locale of LOCALES) {
    await generateLocale(locale);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
