/**
 * Build-bridge: reads content via the Tina-generated client and writes
 * src/data/*.ts in the exact shapes the existing components already consume.
 * Runs after `tinacms build` (see package.json "build" script).
 */
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import client from "../tina/__generated__/client";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(__dirname, "../src/data");

function banner() {
  return "// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.\n";
}

function strLit(s: string) {
  return JSON.stringify(s ?? "");
}

async function main() {
  const [siteRes, servicesRes, casesRes, pricingRes] = await Promise.all([
    client.queries.site({ relativePath: "home.md" }),
    client.queries.serviceConnection(),
    client.queries.caseConnection(),
    client.queries.pricingPlanConnection(),
  ]);

  const services = (servicesRes.data.serviceConnection.edges ?? [])
    .map((e) => e!.node!)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const cases = (casesRes.data.caseConnection.edges ?? [])
    .map((e) => e!.node!)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const pricingPlans = (pricingRes.data.pricingPlanConnection.edges ?? [])
    .map((e) => e!.node!)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const site = siteRes.data.site;

  /* ── src/data/site.ts ───────────────────────────────────────────────── */
  writeFileSync(
    resolve(dataDir, "site.ts"),
    `${banner()}
export const siteData = {
  heroHeadline: ${strLit(site.heroHeadline)},
  heroSubline: ${strLit(site.heroSubline)},
  heroCta: ${strLit(site.heroCta)},
  heroCtaSecondary: ${strLit(site.heroCtaSecondary)},
  clientLogosLabel: ${strLit(site.clientLogosLabel)},
  nav: ${JSON.stringify(
    (site.nav ?? []).map((n) => ({ label: n!.label, href: n!.href })),
    null,
    2
  )},
};
`
  );

  /* ── src/data/services.ts ───────────────────────────────────────────── */
  writeFileSync(
    resolve(dataDir, "services.ts"),
    `${banner()}
export interface Service {
  slug: string;
  title: string;
  description: string;
  gradient: string;
  icon: "code" | "grid" | "palette" | "bot";
}

export const services: Service[] = ${JSON.stringify(
      services.map((s) => ({
        slug: s.slug,
        title: s.title,
        description: s.description,
        gradient: s.gradient,
        icon: s.icon,
      })),
      null,
      2
    )};
`
  );

  /* ── src/data/serviceDetails.ts ──────────────────────────────────────── */
  writeFileSync(
    resolve(dataDir, "serviceDetails.ts"),
    `${banner()}
export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
}

export const serviceDetails: ServiceDetail[] = ${JSON.stringify(
      services.map((s) => ({
        slug: s.slug,
        heroHeadline: s.heroHeadline,
        heroSubline: s.heroSubline,
        heroImage: s.heroImage,
        tags: s.tags ?? [],
        process: (s.process ?? []).map((p) => ({
          number: p!.number,
          title: p!.title,
          description: p!.description,
        })),
        caseTitle: s.caseTitle,
        caseSlug: s.caseSlug,
        caseSubtitle: s.caseSubtitle,
        caseImage: s.caseImage,
        caseStats: (s.caseStats ?? []).map((c) => ({
          value: c!.value,
          label: c!.label,
        })),
        caseDescription: s.caseDescription,
        ctaHeadline: s.ctaHeadline,
        ctaBody: s.ctaBody,
      })),
      null,
      2
    )};
`
  );

  /* ── src/data/cases.ts ───────────────────────────────────────────────── */
  const featured = cases.filter((c) => c.featured);
  const grid = cases.filter((c) => !c.featured);

  writeFileSync(
    resolve(dataDir, "cases.ts"),
    `${banner()}
export interface FeaturedCase {
  slug: string;
  title: string;
  subtitle: string;
  imagePosition: "left" | "right";
  stats: string[];
  image: string;
}

export interface GridCase {
  slug: string;
  title: string;
  subtitle: string;
  image: string;
}

export const featuredCases: FeaturedCase[] = ${JSON.stringify(
      featured.map((c) => ({
        slug: c.slug,
        title: c.title,
        subtitle: c.subtitle,
        imagePosition: c.imagePosition ?? "left",
        stats: c.stats ?? [],
        image: c.image,
      })),
      null,
      2
    )};

export const gridCases: GridCase[] = ${JSON.stringify(
      grid.map((c) => ({
        slug: c.slug,
        title: c.title,
        subtitle: c.subtitle,
        image: c.image,
      })),
      null,
      2
    )};
`
  );

  /* ── src/data/caseDetails.ts ─────────────────────────────────────────── */
  const withDetail = cases.filter((c) => c.heroHeadline && c.description);

  writeFileSync(
    resolve(dataDir, "caseDetails.ts"),
    `${banner()}
export interface CaseDetail {
  slug: string;
  category: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  description: string;
  background: string;
  problem: string;
  solution: string;
  stats: {
    value: string;
    label: string;
  }[];
  mockupImages: string[];
}

export const caseDetailsMap: Record<string, CaseDetail> = ${JSON.stringify(
      Object.fromEntries(
        withDetail.map((c) => [
          c.slug,
          {
            slug: c.slug,
            category: c.category,
            heroHeadline: c.heroHeadline,
            heroSubline: c.heroSubline,
            heroImage: c.heroImage,
            description: c.description,
            background: c.background,
            problem: c.problem,
            solution: c.solution,
            stats: (c.detailStats ?? []).map((s) => ({
              value: s!.value,
              label: s!.label,
            })),
            mockupImages: c.mockupImages ?? [],
          },
        ])
      ),
      null,
      2
    )};

export function getCaseDetail(slug: string): CaseDetail | undefined {
  return caseDetailsMap[slug];
}
`
  );

  /* ── src/data/pricing.ts ─────────────────────────────────────────────── */
  writeFileSync(
    resolve(dataDir, "pricing.ts"),
    `${banner()}
export interface PricingPlan {
  slug: string;
  title: string;
  price: string;
  priceUnit: string;
  badge: string;
  badgeColor: string;
  description: string;
  cta: string;
  features: string[];
}

export const pricingPlans: PricingPlan[] = ${JSON.stringify(
      pricingPlans.map((p) => ({
        slug: p.slug,
        title: p.title,
        price: p.price,
        priceUnit: p.priceUnit,
        badge: p.badge,
        badgeColor: p.badgeColor,
        description: p.description,
        cta: p.cta,
        features: p.features ?? [],
      })),
      null,
      2
    )};
`
  );

  console.log(
    `generate-content: wrote site.ts, services.ts, serviceDetails.ts, cases.ts (${featured.length} featured / ${grid.length} grid), caseDetails.ts (${withDetail.length} with detail), pricing.ts (${pricingPlans.length} plans)`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
