// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface CaseDetail {
  slug: string;
  category: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  description: string;
  background: string;
  problem: string;
  solution: string;
  stats: {
    value: string;
    label: string;
  }[];
  mockupImages: string[];
}

export const caseDetailsMap: Record<string, CaseDetail> = {
  "tap2link": {
    "slug": "tap2link",
    "category": "Digitale Kontakt- & Serviceecosysteme",
    "heroHeadline": "Multifunktionale App für Events, Services & Teams",
    "heroSubline": "Ein digitales Serviceportal für komplexe B2B-Prozesse in nur 8 Wochen.",
    "heroImage": "/uploads/cases/tap2link-hero.png",
    "description": "Tap2Link ist eine vollständig neue, multifunktionale Plattform für Events, Services und Teams. Wir haben die Anwendung von Grund auf mit modernem Design und nutzerfreundlicher Oberfläche entwickelt.",
    "background": "Die ursprüngliche Plattform war technisch veraltet und konnte die wachsenden Anforderungen der Nutzer nicht erfüllen. Das Unternehmen benötigte eine Komplettneubau mit neuem Design-System.",
    "problem": "Viele Anforderungen, unklare Priorisierung, Verschiedene Stakeholder mit unterschiedlichen Visionen, Technische Schulden aus Legacy-Code, Knappe Zeitvorgaben.",
    "solution": "Modulare App-Architektur mit sauberer Separation of Concerns, Modernes React-Stack mit TypeScript für Typ-Sicherheit, Iterative Entwicklung mit wöchentlichen Reviews, Agile Priorisierung mit klarer Nutzer-Fokussierung, Design-System für schnelle Konsistenz.",
    "stats": [
      {
        "value": "+300%",
        "label": "mehr App-Installationen nach Launch"
      },
      {
        "value": "5 Sek",
        "label": "bis zum vollständigen Profilein Upload via NFC"
      },
      {
        "value": "+60%",
        "label": "Conversion bei Messegesprächsterminen"
      }
    ],
    "mockupImages": [
      "/uploads/cases/tap2link-mockup-1.png",
      "/uploads/cases/tap2link-mockup-3.png"
    ]
  },
  "brylliant": {
    "slug": "brylliant",
    "category": "Design Systeme & UX-Tools",
    "heroHeadline": "Das Tool für perfekte Briefings",
    "heroSubline": "Ein skalierbares Tool für effiziente Briefings, saubere Prozesse und strategische Klarheit – designed in 6 Wochen.",
    "heroImage": "/uploads/cases/brylliant-hero.png",
    "description": "Brylliant ist ein Briefing-Tool, das Agenturen und Kunden auf eine gemeinsame Grundlage bringt. Wir haben Interface und Workflow von Grund auf neu gedacht, damit Briefings nicht mehr Glückssache sind.",
    "background": "Briefings liefen bisher über unstrukturierte Dokumente und E-Mail-Ketten. Wichtige Informationen gingen verloren, Rückfragen kosteten Zeit und Nerven auf beiden Seiten.",
    "problem": "Uneinheitliche Briefing-Formate, fehlende Pflichtfelder, viele Rückfragerunden, kein zentraler Ort für Status und Freigaben, wachsender Frust bei Kunden und Agenturen.",
    "solution": "Geführte Briefing-Formulare mit klaren Pflichtfeldern, zentrales Dashboard für Status und Freigaben, Design System für konsistente Bedienung, enge Abstimmung mit echten Nutzern in jeder Iteration.",
    "stats": [
      {
        "value": "2×",
        "label": "schnellere Briefing-Freigaben"
      },
      {
        "value": "95%",
        "label": "weniger Rückfragen von Agenturen"
      },
      {
        "value": "+60%",
        "label": "höhere Nutzerzufriedenheit"
      }
    ],
    "mockupImages": [
      "/uploads/cases/brylliant-mockup-1.png"
    ]
  },
  "moerschen": {
    "slug": "moerschen",
    "category": "Website-Relaunch & Company Building",
    "heroHeadline": "Vom Relaunch zur Leadmaschine",
    "heroSubline": "Website-Relaunch mit klarer Nutzerführung und neuer Kommunikationsstrategie – in 8 Wochen live.",
    "heroImage": "/uploads/cases/moerschen-hero.png",
    "description": "Moerschen brauchte eine Website, die komplexe Industrieleistungen verständlich macht und Interessenten direkt zum richtigen Ansprechpartner führt. Wir haben Informationsarchitektur, Design und Content komplett neu aufgesetzt.",
    "background": "Die alte Website war historisch gewachsen, unübersichtlich und technisch in die Jahre gekommen. Besucher fanden weder passende Ansprechpartner noch die richtigen Leistungen.",
    "problem": "Unklare Navigation, veraltetes Design, fehlende klare Calls-to-Action, lange Wege zu Ansprechpartnern, kein einheitliches Markenbild über alle Bereiche.",
    "solution": "Neue Informationsarchitektur entlang der Kundenreise, klar geführte Kontaktwege zu Ansprechpartnern, modernes Design-System, iterative Umsetzung mit wöchentlichem Feedback bis zum Launch nach 8 Wochen.",
    "stats": [
      {
        "value": "+45%",
        "label": "mehr Kontaktanfragen"
      },
      {
        "value": "8 Wo.",
        "label": "vom Kickoff bis Launch"
      },
      {
        "value": "2×",
        "label": "schnellere Ansprechpartner-Suche"
      }
    ],
    "mockupImages": [
      "/uploads/cases/moerschen-mockup-1.png"
    ]
  },
  "machinemaster": {
    "slug": "machinemaster",
    "category": "KI-gestützte Vertriebstools",
    "heroHeadline": "KI im Vertrieb von Landmaschinen",
    "heroSubline": "Ein KI-gestütztes Vertriebstool für Händler und Außendienst – vom MVP in nur 12 Wochen.",
    "heroImage": "/uploads/cases/machinemaster-hero.png",
    "description": "MachineMaster unterstützt Händler und Außendienst beim Verkauf von Landmaschinen mit KI-gestützter Produktberatung. Wir haben das MVP von der ersten Idee bis zum Rollout in 12 Wochen gebaut.",
    "background": "Außendienstler mussten umfangreiche Produktkataloge und technische Spezifikationen im Kopf haben, um Kunden vor Ort kompetent beraten zu können. Das kostete Zeit und führte zu Unsicherheit im Verkaufsgespräch.",
    "problem": "Komplexe Produktwelten, hohe Beratungsanforderungen im Außendienst, fehlender schneller Zugriff auf passende Maschinenkonfigurationen, hoher Schulungsaufwand für neue Mitarbeiter.",
    "solution": "KI-gestützter Produktberater mit natürlicher Sprachsuche, mobile-first Anwendung für den Einsatz vor Ort, Integration mit bestehenden Produktdaten, iterative Entwicklung mit echtem Vertriebsteam als Testnutzer.",
    "stats": [
      {
        "value": "+230%",
        "label": "mehr Nutzerinteraktionen"
      },
      {
        "value": "+10%",
        "label": "Verkaufssteigerung"
      },
      {
        "value": "5/5",
        "label": "Kundenbewertungen"
      }
    ],
    "mockupImages": [
      "/uploads/cases/machinemaster-mockup-1.png"
    ]
  }
};

export function getCaseDetail(slug: string): CaseDetail | undefined {
  return caseDetailsMap[slug];
}
