// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface FeaturedCase {
  slug: string;
  title: string;
  subtitle: string;
  imagePosition: "left" | "right";
  stats: string[];
  image: string;
}

export interface GridCase {
  slug: string;
  title: string;
  subtitle: string;
  image: string;
}

export const featuredCases: FeaturedCase[] = [
  {
    "slug": "tap2link",
    "title": "Tap2Link – Mehr als eine digitale Visitenkarte.",
    "subtitle": "Ein digitales Serviceportal für komplexe B2B-Prozesse in nur 8 Wochen.",
    "imagePosition": "right",
    "stats": [
      "+230% Nutzerinteraktion",
      "Launch in 16 Wochen",
      "95% Kundenzufriedenheit"
    ],
    "image": "/uploads/cases/tap2link-card.png"
  },
  {
    "slug": "brylliant",
    "title": "Brylliant – das Tool für perfekte Briefings",
    "subtitle": "Ein skalierbares Tool für effiziente Briefings, saubere Prozesse und strategische Klarheit.",
    "imagePosition": "left",
    "stats": [
      "Strukturierte Vorlagen & geführte Briefings",
      "2x schnellere Briefing-Freigaben",
      "95 % weniger Rückfragen von Agenturen"
    ],
    "image": "/uploads/cases/brylliant-card.png"
  },
  {
    "slug": "moerschen",
    "title": "Moerschen – Website-Relaunch für bessere Kommunikation",
    "subtitle": "Ein digitales Serviceportal für komplexe B2B-Prozesse in nur 8 Wochen.",
    "imagePosition": "right",
    "stats": [
      "45 % mehr Kontaktanfragen über die Website",
      "Nutzer finden Ansprechpersonen 2× schneller als vorher",
      "8 Wochen vom Kickoff bis Livegang"
    ],
    "image": "/uploads/cases/moerschen-card.png"
  },
  {
    "slug": "machinemaster",
    "title": "MachineMaster – Landmaschinen Vertriebsplattform",
    "subtitle": "Ein digitales Vertriebstool für Händler, Vertrieb & Außendienst – zum MVP in nur 12 Wochen",
    "imagePosition": "left",
    "stats": [
      "+230 % Nutzerinteraktionen",
      "Verkaufssteigerung um 10%",
      "5/5 Sternen in den Bewertungen"
    ],
    "image": "/uploads/cases/machinemaster-card.png"
  }
];

export const gridCases: GridCase[] = [
  {
    "slug": "neuer-look",
    "title": "Neuer Look, neue Webseite",
    "subtitle": "Ein kompletter Webseiten-Relaunch für einen frischen Markenauftritt in wenigen Wochen.",
    "image": "/uploads/cases/neuer-look-card.png"
  },
  {
    "slug": "creator-studios",
    "title": "Creator Studio – Buchungsplattform für kreative Räume",
    "subtitle": "Eine reduzierte Booking-Website für ein Fotostudio in Düsseldorf, die Anfragen in direkte Buchungen verwandelt.",
    "image": "/uploads/cases/animation-card.png"
  },
  {
    "slug": "scanservice",
    "title": "Dein ScanService",
    "subtitle": "Eine digitale Plattform, die das Scannen und Verwalten von Dokumenten so einfach macht wie nie.",
    "image": "/uploads/cases/scanservice-card.png"
  }
];
