// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface Service {
  slug: string;
  title: string;
  description: string;
  gradient: string;
  icon: "code" | "grid" | "palette" | "bot";
}

export const services: Service[] = [
  {
    "slug": "development",
    "title": "Produktentwicklung / Development",
    "description": "Webapps, Portale, SaaS – technisch solide, schnell live.",
    "gradient": "linear-gradient(146.383deg, rgba(163, 24, 248, 0.8) 0%, rgba(163, 24, 248, 0) 100%)",
    "icon": "code"
  },
  {
    "slug": "company-building",
    "title": "Company Building",
    "description": "Wir helfen Teams beim Aufbau neuer Geschäftsmodelle und MVPs.",
    "gradient": "linear-gradient(268.344deg, rgba(255, 0, 0, 0.8) 0%, rgba(255, 0, 0, 0) 100%)",
    "icon": "grid"
  },
  {
    "slug": "webdesign",
    "title": "Webdesign & UX",
    "description": "Visuell stark, funktional gedacht – UX, UI, Markenführung.",
    "gradient": "linear-gradient(44.336deg, rgba(43, 149, 246, 0.8) 0%, rgba(43, 149, 246, 0) 100%)",
    "icon": "palette"
  },
  {
    "slug": "ki-strategie",
    "title": "KI Strategie",
    "description": "OpenAI, Gemini, Zapier & Make – wir verbinden Mensch & Maschine.",
    "gradient": "linear-gradient(-56.458deg, rgba(253, 167, 0, 0.8) 0%, rgba(253, 167, 0, 0) 100%)",
    "icon": "bot"
  }
];
