// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
}

export const serviceDetails: ServiceDetail[] = [
  {
    "slug": "development",
    "heroHeadline": "Vom digitalen Produkt zum selbstlernenden System",
    "heroSubline": "Wir kommen aus der Softwareentwicklung – und nutzen dieses Fundament, um Produkte zu bauen, die sich mit KI weiterentwickeln, statt zu stagnieren.",
    "heroImage": "/uploads/services/development-hero.png",
    "tags": [
      "Beratung: erfahrenes Entwickler-Team, menschlich & ehrlich",
      "Umsetzung: KI-gestützte Entwicklung & Automatisierung",
      "Selbstlernende Features statt starrer Software",
      "Launch-ready in 4–16 Wochen"
    ],
    "process": [
      {
        "number": "01",
        "title": "Discovery & Strategie",
        "description": "Wir hören zu und verstehen dein Business im direkten Gespräch, nicht per Fragebogen. Ehrliche Beratung von Menschen, die selbst gebaut haben."
      },
      {
        "number": "02",
        "title": "Architektur & KI-Konzept",
        "description": "Wir entscheiden gemeinsam, wo klassische Software reicht und wo ein selbstlernendes System oder ein KI-Agent den Unterschied macht."
      },
      {
        "number": "03",
        "title": "Prototyping mit KI-Unterstützung",
        "description": "Unsere Entwickler:innen nutzen KI-Tools, um Prototypen in Tagen statt Wochen zu bauen – validiert an echten Nutzern."
      },
      {
        "number": "04",
        "title": "Entwicklung & Automatisierung",
        "description": "Wo früher Zeile für Zeile programmiert wurde, übernehmen heute KI-Agenten wiederkehrende Aufgaben – wir bauen die Werkzeuge, die weitere Werkzeuge schaffen."
      },
      {
        "number": "05",
        "title": "Launch & kontinuierliches Lernen",
        "description": "Nach dem Launch hört die Entwicklung nicht auf: Das System lernt aus echten Daten weiter und wird automatisiert optimiert."
      }
    ],
    "caseTitle": "Tap2Link",
    "caseSlug": "tap2link",
    "caseSubtitle": "Tap2Link: Mehr als eine digitale Visitenkarte.",
    "caseImage": "/uploads/services/development-case.png",
    "caseStats": [
      {
        "value": "+35%",
        "label": "Schnellerer Onboarding-Prozess"
      },
      {
        "value": "-20%",
        "label": "Reduzierter Support-Aufwand"
      },
      {
        "value": "+40%",
        "label": "Mehr Nutzerinteraktionen"
      }
    ],
    "caseDescription": "Ein digitales Serviceportal für komplexe B2B-Prozesse – in nur 8 Wochen von der Idee bis zum Launch.",
    "ctaHeadline": "Bereit für ein Produkt, das mitdenkt?",
    "ctaBody": "Lass uns in einem ehrlichen Erstgespräch herausfinden, ob dein nächstes Produkt klassische Software oder ein selbstlernendes System braucht."
  },
  {
    "slug": "company-building",
    "heroHeadline": "Von der Idee zum KI-gestützten Unternehmen",
    "heroSubline": "Geschäftsmodell-Beratung bleibt Vertrauenssache zwischen Menschen. Für die Umsetzung setzen wir auf KI, um dein MVP schneller und schlanker an den Start zu bringen.",
    "heroImage": "/uploads/services/company-building-hero.png",
    "tags": [
      "Geschäftsmodell-Beratung von erfahrenen Gründer:innen",
      "MVP-Umsetzung mit KI-gestützter Entwicklung",
      "Automatisierte Prozesse statt manueller Handarbeit",
      "MVP in 8–16 Wochen live"
    ],
    "process": [
      {
        "number": "01",
        "title": "Idee & Vision",
        "description": "Im persönlichen Gespräch schärfen wir deine Idee: echtes Problem, echte Zielgruppe, echter USP."
      },
      {
        "number": "02",
        "title": "Geschäftsmodell-Beratung",
        "description": "Lean Canvas und Revenue-Modell entstehen im Dialog mit unserem Team – keine automatisierte Vorlage, sondern echte unternehmerische Erfahrung."
      },
      {
        "number": "03",
        "title": "MVP-Scope mit KI-Fokus",
        "description": "Wir definieren, welche Prozesse dein Unternehmen von Anfang an automatisieren und mit KI-Agenten skalieren kann."
      },
      {
        "number": "04",
        "title": "Build & Automatisierung",
        "description": "Unser Team baut dein MVP – Design, Entwicklung, Automatisierungen. KI übernimmt, was sich wiederholt, damit du dich aufs Wachstum konzentrierst."
      },
      {
        "number": "05",
        "title": "Traction & Skalierung",
        "description": "Wir begleiten die ersten Nutzer, das erste Feedback, die ersten Umsätze – und helfen, KI-gestützte Prozesse in deinem eigenen Team zu verankern."
      }
    ],
    "caseTitle": "Moerschen",
    "caseSlug": "moerschen",
    "caseSubtitle": "Moerschen: Vom Relaunch zur Leadmaschine.",
    "caseImage": "/uploads/services/company-building-case.png",
    "caseStats": [
      {
        "value": "+45%",
        "label": "Mehr Kontaktanfragen"
      },
      {
        "value": "8 Wo.",
        "label": "Vom Kickoff bis Launch"
      },
      {
        "value": "2×",
        "label": "Schnellere Ansprechpartner-Suche"
      }
    ],
    "caseDescription": "Website-Relaunch mit klarer Nutzerführung und neuer Kommunikationsstrategie – in 8 Wochen live.",
    "ctaHeadline": "Dein Startup. Unsere Erfahrung. KI als Beschleuniger.",
    "ctaBody": "Lass uns im kostenlosen Erstgespräch herausfinden, wie wir dein Geschäftsmodell mit echter Erfahrung und smarter Automatisierung in die Realität umsetzen."
  },
  {
    "slug": "webdesign",
    "heroHeadline": "Design, das mit deinen Nutzern mitlernt",
    "heroSubline": "Gute UX beginnt mit echtem Zuhören – das bleibt Handarbeit. Für Umsetzung und Personalisierung nutzen wir KI, damit dein Interface sich weiterentwickelt.",
    "heroImage": "/uploads/services/webdesign-hero.png",
    "tags": [
      "UX-Beratung im direkten Gespräch mit unserem Team",
      "KI-gestützte Design-Systeme & Content-Erstellung",
      "Personalisierte Interfaces statt statischer Screens",
      "Von der Skizze zum Live-Interface in 4–8 Wochen"
    ],
    "process": [
      {
        "number": "01",
        "title": "UX Research & Analyse",
        "description": "Nutzerinterviews und Wettbewerbsanalyse – geführt von echten Menschen, die zuhören, nicht von einem Fragebogen-Tool."
      },
      {
        "number": "02",
        "title": "Informationsarchitektur",
        "description": "Gemeinsam legen wir fest, wie Nutzer:innen sich orientieren – die Grundlage für jedes gute Interface, ob klassisch oder KI-gestützt."
      },
      {
        "number": "03",
        "title": "Konzept mit KI-Unterstützung",
        "description": "Unsere Designer:innen nutzen KI-Tools für schnellere Wireframes und Varianten – die Entscheidung bleibt beim Menschen."
      },
      {
        "number": "04",
        "title": "Visual Design & Design-System",
        "description": "Ein Design-System, das mit KI-gestützten Komponenten mitwächst, statt bei jedem neuen Feature von Null zu starten."
      },
      {
        "number": "05",
        "title": "Handoff & lernende Optimierung",
        "description": "Nach dem Launch messen wir, wie Nutzer:innen das Interface tatsächlich verwenden – und optimieren datenbasiert weiter."
      }
    ],
    "caseTitle": "Brylliant",
    "caseSlug": "brylliant",
    "caseSubtitle": "Brylliant: Das Tool für perfekte Briefings.",
    "caseImage": "/uploads/services/webdesign-case.png",
    "caseStats": [
      {
        "value": "2×",
        "label": "Schnellere Briefing-Freigaben"
      },
      {
        "value": "95%",
        "label": "Weniger Rückfragen"
      },
      {
        "value": "+60%",
        "label": "Höhere Nutzerzufriedenheit"
      }
    ],
    "caseDescription": "Ein skalierbares Tool für effiziente Briefings, saubere Prozesse und strategische Klarheit – designed in 6 Wochen.",
    "ctaHeadline": "Design, das nicht stehen bleibt.",
    "ctaBody": "Lass uns in einem ehrlichen Erstgespräch zeigen, wie durchdachtes UX-Design und smarte KI-Tools zusammen mehr Wirkung erzielen."
  },
  {
    "slug": "ki-strategie",
    "heroHeadline": "Wir bauen die Werkzeuge, die neue Werkzeuge schaffen",
    "heroSubline": "Als Software-Team kennen wir die Fallstricke von KI-Projekten aus erster Hand. Die Beratung führen wir persönlich, die Automatisierung übernehmen selbstlernende Systeme und KI-Agenten.",
    "heroImage": "/uploads/services/ki-strategie-hero.png",
    "tags": [
      "KI-Readiness-Beratung mit erfahrenem Software-Team",
      "Custom KI-Agenten & selbstlernende Workflows",
      "Weitgehende Automatisierung statt Insellösungen",
      "Erster Prototyp in 2–4 Wochen"
    ],
    "process": [
      {
        "number": "01",
        "title": "KI-Readiness Assessment",
        "description": "Wir schauen uns ehrlich an, wo dein Unternehmen steht – Prozesse, Daten, Tech-Stack. Keine Buzzword-Analyse, sondern ein ehrliches Gespräch."
      },
      {
        "number": "02",
        "title": "Use-Case-Priorisierung",
        "description": "Gemeinsam entscheiden wir, welche Prozesse sich wirklich für KI-Agenten eignen – und welche (noch) nicht."
      },
      {
        "number": "03",
        "title": "Prototyping selbstlernender Systeme",
        "description": "Wir bauen einen funktionierenden Agenten oder Automatisierungs-Workflow in 2–4 Wochen, der aus echten Daten lernt."
      },
      {
        "number": "04",
        "title": "Integration & Rollout",
        "description": "Von der Idee in die Produktion: Wir integrieren KI-Agenten so, dass sie deinen bestehenden Stack automatisieren, nicht ersetzen."
      },
      {
        "number": "05",
        "title": "Monitoring & Weiterentwicklung",
        "description": "Selbstlernende Systeme sind nie 'fertig'. Wir begleiten den Betrieb, messen Ergebnisse und lassen die Systeme kontinuierlich dazulernen."
      }
    ],
    "caseTitle": "MachineMaster",
    "caseSlug": "machinemaster",
    "caseSubtitle": "MachineMaster: KI im Vertrieb von Landmaschinen.",
    "caseImage": "/uploads/services/ki-strategie-case.png",
    "caseStats": [
      {
        "value": "+230%",
        "label": "Mehr Nutzerinteraktionen"
      },
      {
        "value": "+10%",
        "label": "Verkaufssteigerung"
      },
      {
        "value": "5/5",
        "label": "Kundenbewertungen"
      }
    ],
    "caseDescription": "Ein KI-gestütztes Vertriebstool für Händler und Außendienst – vom MVP in nur 12 Wochen.",
    "ctaHeadline": "KI, die wirklich automatisiert – nicht nur ein Chatbot.",
    "ctaBody": "Im kostenlosen Erstgespräch mit unserem Team sprechen wir ehrlich darüber, wo KI-Agenten in deinem Business heute schon den Unterschied machen."
  }
];
