// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export type PulseStep = "check" | "build" | "care";

export interface Service {
  slug: string;
  title: string;
  description: string;
  gradient: string;
  icon: "code" | "grid" | "palette" | "bot";
  tags: string[];
  usedIn: PulseStep[];
  proof: string;
}

export const services: Service[] = [
  {
    "slug": "ai-automation",
    "title": "AI Automation",
    "description": "Bestehende Prozesse neu denken: Wir verwandeln manuelle Geschäftsprozesse in intelligente, integrierte Workflows.",
    "gradient": "linear-gradient(-56.458deg, rgba(253, 167, 0, 0.8) 0%, rgba(253, 167, 0, 0) 100%)",
    "icon": "bot",
    "tags": [
      "AI Agents & intelligente Workflows",
      "Automatisierung von E-Mail- und Dokumentenprozessen",
      "Wissens- und Recherche-Systeme",
      "Automatisierung von Vertrieb, Service & Operations",
      "Integration in ERP, CRM, DMS & bestehende Tools",
      "Betrieb und kontinuierliche Weiterentwicklung"
    ],
    "usedIn": [
      "check",
      "build",
      "care"
    ],
    "proof": "Angebote, die früher drei Tage brauchten, gehen jetzt in Minuten raus."
  },
  {
    "slug": "ai-products",
    "title": "AI Products",
    "description": "Neue digitale Produkte bauen: Wir entwickeln Produkte, die AI nicht nachträglich aufsetzen, sondern von Anfang an mitdenken.",
    "gradient": "linear-gradient(146.383deg, rgba(163, 24, 248, 0.8) 0%, rgba(163, 24, 248, 0) 100%)",
    "icon": "code",
    "tags": [
      "Produktstrategie & Konzept",
      "AI-native Produktentwicklung",
      "Prototyping & MVPs",
      "Web Apps & Business Software",
      "AI-Architektur & Integrationen",
      "Launch & kontinuierliche Weiterentwicklung"
    ],
    "usedIn": [
      "build",
      "care"
    ],
    "proof": "Aus einer Excel-Liste wurde ein Produkt, das Kunden selbst bedienen."
  },
  {
    "slug": "ai-experience",
    "title": "AI Experience",
    "description": "Die Zusammenarbeit von Mensch und AI gestalten: Wir gestalten Interfaces, Workflows und Interaktionen für eine neue Generation digitaler Produkte.",
    "gradient": "linear-gradient(44.336deg, rgba(43, 149, 246, 0.8) 0%, rgba(43, 149, 246, 0) 100%)",
    "icon": "palette",
    "tags": [
      "AI Interaction Design",
      "Agent UX & Conversational Interfaces",
      "UX für komplexe B2B-Prozesse",
      "Product Design & Prototyping",
      "Design Systems",
      "Evaluation & Optimierung"
    ],
    "usedIn": [
      "check",
      "build"
    ],
    "proof": "Ein Interface, das zeigt, was die KI gerade tut – und warum."
  },
  {
    "slug": "venture-building",
    "title": "Venture Building",
    "description": "Aus Chancen neue Geschäfte machen: Wir validieren Geschäftsmodelle und bauen daraus funktionierende digitale Ventures.",
    "gradient": "linear-gradient(268.344deg, rgba(255, 0, 0, 0.8) 0%, rgba(255, 0, 0, 0) 100%)",
    "icon": "grid",
    "tags": [
      "Opportunity Discovery",
      "Geschäftsmodell & Strategie",
      "Markt- und Konzeptvalidierung",
      "MVP & Product Development",
      "AI-native Products",
      "Launch & Growth"
    ],
    "usedIn": [
      "check",
      "build",
      "care"
    ],
    "proof": "Aus einer Idee im Nebensatz wurde ein eigenes Geschäft."
  }
];
