// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface ServiceDetail {
  slug: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  tags: string[];
  process: ProcessStep[];
  caseTitle: string;
  caseSlug: string;
  caseSubtitle: string;
  caseImage: string;
  caseStats: CaseStat[];
  caseDescription: string;
  ctaHeadline: string;
  ctaBody: string;
  ctaButtonLabel: string;
}

export const serviceDetails: ServiceDetail[] = [
  {
    "slug": "ai-automation",
    "heroHeadline": "Improve the business.",
    "heroSubline": "Wir automatisieren Prozesse dort, wo KI messbar Zeit, Kosten und Fehler reduziert.",
    "heroImage": "/uploads/services/ai-automation-hero.png",
    "tags": [
      "AI Agents & intelligente Workflows",
      "Automatisierung von E-Mail- und Dokumentenprozessen",
      "Wissens- und Recherche-Systeme",
      "Automatisierung von Vertrieb, Service & Operations",
      "Integration in ERP, CRM, DMS & bestehende Tools",
      "Betrieb und kontinuierliche Weiterentwicklung"
    ],
    "process": [
      {
        "number": "01",
        "title": "Diagnose",
        "description": "Wir analysieren Daten, Prozesse, Team und Tools in 1–2 Tagen und zeigen, wo KI den größten Hebel bietet."
      },
      {
        "number": "02",
        "title": "Empfehlung",
        "description": "Sie erhalten eine priorisierte Roadmap statt einer generischen Strategiepräsentation."
      },
      {
        "number": "03",
        "title": "Umsetzung",
        "description": "Wir bauen die 1–3 wichtigsten Anwendungsfälle in einem 4-wöchigen Sprint."
      },
      {
        "number": "04",
        "title": "Begleitung",
        "description": "Danach bleiben wir dran: monatliche Check-ins, ein Dashboard und vierteljährliche Reviews."
      }
    ],
    "caseTitle": "MachineMaster",
    "caseSlug": "machinemaster",
    "caseSubtitle": "MachineMaster: KI im Vertrieb von Landmaschinen.",
    "caseImage": "/uploads/services/ai-automation-case.png",
    "caseStats": [
      {
        "value": "+230%",
        "label": "Mehr Nutzerinteraktionen"
      },
      {
        "value": "+10%",
        "label": "Verkaufssteigerung"
      },
      {
        "value": "5/5",
        "label": "Kundenbewertungen"
      }
    ],
    "caseDescription": "Ein KI-gestütztes Vertriebstool für Händler und Außendienst – vom MVP in nur 12 Wochen.",
    "ctaHeadline": "KI, die wirklich automatisiert – nicht nur ein Chatbot.",
    "ctaBody": "Im kostenlosen Erstgespräch mit unserem Team sprechen wir ehrlich darüber, wo KI-Agenten in deinem Business heute schon den Unterschied machen.",
    "ctaButtonLabel": "Find your automation opportunity"
  },
  {
    "slug": "ai-products",
    "heroHeadline": "Build the product.",
    "heroSubline": "Digitale Produkte, bei denen KI von Anfang an Teil des Produkts ist.",
    "heroImage": "/uploads/services/ai-products-hero.png",
    "tags": [
      "Produktstrategie & Konzept",
      "AI-native Produktentwicklung",
      "Prototyping & MVPs",
      "Web Apps & Business Software",
      "AI-Architektur & Integrationen",
      "Launch & kontinuierliche Weiterentwicklung"
    ],
    "process": [
      {
        "number": "01",
        "title": "Bestandsaufnahme",
        "description": "Bestandsaufnahme deines Produkts oder deiner Idee."
      },
      {
        "number": "02",
        "title": "Teilprojekte",
        "description": "Zum Beispiel Datenhaltung, Auswertungen oder Kundeninteraktions-Tools."
      },
      {
        "number": "03",
        "title": "Laufende Weiterentwicklung",
        "description": "Laufende Weiterentwicklung statt eines vermeintlich „fertigen” Produkts."
      }
    ],
    "caseTitle": "Tap2Link",
    "caseSlug": "tap2link",
    "caseSubtitle": "Tap2Link: Mehr als eine digitale Visitenkarte.",
    "caseImage": "/uploads/services/ai-products-case.png",
    "caseStats": [
      {
        "value": "+35%",
        "label": "Schnellerer Onboarding-Prozess"
      },
      {
        "value": "-20%",
        "label": "Reduzierter Support-Aufwand"
      },
      {
        "value": "+40%",
        "label": "Mehr Nutzerinteraktionen"
      }
    ],
    "caseDescription": "Ein digitales Serviceportal für komplexe B2B-Prozesse – in nur 8 Wochen von der Idee bis zum Launch.",
    "ctaHeadline": "Bereit für ein Produkt, das mitdenkt?",
    "ctaBody": "Lass uns in einem ehrlichen Erstgespräch herausfinden, ob dein nächstes Produkt klassische Software oder ein selbstlernendes System braucht.",
    "ctaButtonLabel": "Build your product"
  },
  {
    "slug": "ai-experience",
    "heroHeadline": "Design the interaction.",
    "heroSubline": "Neue Interfaces für die Zusammenarbeit von Menschen und intelligenten Systemen.",
    "heroImage": "/uploads/services/ai-experience-hero.png",
    "tags": [
      "AI Interaction Design",
      "Agent UX & Conversational Interfaces",
      "UX für komplexe B2B-Prozesse",
      "Product Design & Prototyping",
      "Design Systems",
      "Evaluation & Optimierung"
    ],
    "process": [
      {
        "number": "01",
        "title": "UX Research & Analyse",
        "description": "Nutzerinterviews und Wettbewerbsanalyse – geführt von echten Menschen, die zuhören, nicht von einem Fragebogen-Tool."
      },
      {
        "number": "02",
        "title": "Informationsarchitektur",
        "description": "Gemeinsam legen wir fest, wie Nutzer:innen sich orientieren – die Grundlage für jedes gute Interface, ob klassisch oder KI-gestützt."
      },
      {
        "number": "03",
        "title": "Konzept mit KI-Unterstützung",
        "description": "Unsere Designer:innen nutzen KI-Tools für schnellere Wireframes und Varianten – die Entscheidung bleibt beim Menschen."
      },
      {
        "number": "04",
        "title": "Visual Design & Design-System",
        "description": "Ein Design-System, das mit KI-gestützten Komponenten mitwächst, statt bei jedem neuen Feature von Null zu starten."
      },
      {
        "number": "05",
        "title": "Handoff & lernende Optimierung",
        "description": "Nach dem Launch messen wir, wie Nutzer:innen das Interface tatsächlich verwenden – und optimieren datenbasiert weiter."
      }
    ],
    "caseTitle": "Brylliant",
    "caseSlug": "brylliant",
    "caseSubtitle": "Brylliant: Das Tool für perfekte Briefings.",
    "caseImage": "/uploads/services/ai-experience-case.png",
    "caseStats": [
      {
        "value": "2×",
        "label": "Schnellere Briefing-Freigaben"
      },
      {
        "value": "95%",
        "label": "Weniger Rückfragen"
      },
      {
        "value": "+60%",
        "label": "Höhere Nutzerzufriedenheit"
      }
    ],
    "caseDescription": "Ein skalierbares Tool für effiziente Briefings, saubere Prozesse und strategische Klarheit – designed in 6 Wochen.",
    "ctaHeadline": "Design, das nicht stehen bleibt.",
    "ctaBody": "Lass uns in einem ehrlichen Erstgespräch zeigen, wie durchdachtes UX-Design und smarte KI-Tools zusammen mehr Wirkung erzielen.",
    "ctaButtonLabel": "Design your AI experience"
  },
  {
    "slug": "venture-building",
    "heroHeadline": "Create the new business.",
    "heroSubline": "Von der Opportunity zum validierten Geschäftsmodell und funktionierenden Venture.",
    "heroImage": "/uploads/services/venture-building-hero.png",
    "tags": [
      "Opportunity Discovery",
      "Geschäftsmodell & Strategie",
      "Markt- und Konzeptvalidierung",
      "MVP & Product Development",
      "AI-native Products",
      "Launch & Growth"
    ],
    "process": [
      {
        "number": "01",
        "title": "Idee & Vision",
        "description": "Im persönlichen Gespräch schärfen wir deine Idee: echtes Problem, echte Zielgruppe, echter USP."
      },
      {
        "number": "02",
        "title": "Geschäftsmodell-Beratung",
        "description": "Lean Canvas und Revenue-Modell entstehen im Dialog mit unserem Team – keine automatisierte Vorlage, sondern echte unternehmerische Erfahrung."
      },
      {
        "number": "03",
        "title": "MVP-Scope mit KI-Fokus",
        "description": "Wir definieren, welche Prozesse dein Unternehmen von Anfang an automatisieren und mit KI-Agenten skalieren kann."
      },
      {
        "number": "04",
        "title": "Build & Automatisierung",
        "description": "Unser Team baut dein MVP – Design, Entwicklung, Automatisierungen. KI übernimmt, was sich wiederholt, damit du dich aufs Wachstum konzentrierst."
      },
      {
        "number": "05",
        "title": "Traction & Skalierung",
        "description": "Wir begleiten die ersten Nutzer, das erste Feedback, die ersten Umsätze – und helfen, KI-gestützte Prozesse in deinem eigenen Team zu verankern."
      }
    ],
    "caseTitle": "Moerschen",
    "caseSlug": "moerschen",
    "caseSubtitle": "Moerschen: Vom Relaunch zur Leadmaschine.",
    "caseImage": "/uploads/services/venture-building-case.png",
    "caseStats": [
      {
        "value": "+45%",
        "label": "Mehr Kontaktanfragen"
      },
      {
        "value": "8 Wo.",
        "label": "Vom Kickoff bis Launch"
      },
      {
        "value": "2×",
        "label": "Schnellere Ansprechpartner-Suche"
      }
    ],
    "caseDescription": "Website-Relaunch mit klarer Nutzerführung und neuer Kommunikationsstrategie – in 8 Wochen live.",
    "ctaHeadline": "Dein Startup. Unsere Erfahrung. KI als Beschleuniger.",
    "ctaBody": "Lass uns im kostenlosen Erstgespräch herausfinden, wie wir dein Geschäftsmodell mit echter Erfahrung und smarter Automatisierung in die Realität umsetzen.",
    "ctaButtonLabel": "Build a new venture"
  }
];
