// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export const siteData = {
  heroHeadline: "We build what's next.",
  heroSubline: "Wir helfen Unternehmen, mit KI neue Möglichkeiten zu entdecken, zu entwickeln und zu skalieren.",
  heroCta: "Start with AI Pulse",
  heroCtaSecondary: "Talk to us",
  clientLogosLabel: "Diese Kunden setzen auf uns",
};
