// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export interface CaseDetail {
  slug: string;
  category: string;
  heroHeadline: string;
  heroSubline: string;
  heroImage: string;
  description: string;
  background: string;
  problem: string;
  solution: string;
  stats: {
    value: string;
    label: string;
  }[];
  mockupImages: string[];
}

export const caseDetailsMap: Record<string, CaseDetail> = {
  "tap2link": {
    "slug": "tap2link",
    "category": "Digitale Kontakt- & Serviceecosysteme",
    "heroHeadline": "Multifunktionale App für Events, Services & Teams",
    "heroSubline": "Ein digitales Serviceportal für komplexe B2B-Prozesse in nur 8 Wochen.",
    "heroImage": "/uploads/cases/tap2link-hero.png",
    "description": "Tap2Link ist eine vollständig neue, multifunktionale Plattform für Events, Services und Teams. Wir haben die Anwendung von Grund auf mit modernem Design und nutzerfreundlicher Oberfläche entwickelt.",
    "background": "Die ursprüngliche Plattform war technisch veraltet und konnte die wachsenden Anforderungen der Nutzer nicht erfüllen. Das Unternehmen benötigte eine Komplettneubau mit neuem Design-System.",
    "problem": "Viele Anforderungen, unklare Priorisierung, Verschiedene Stakeholder mit unterschiedlichen Visionen, Technische Schulden aus Legacy-Code, Knappe Zeitvorgaben.",
    "solution": "Modulare App-Architektur mit sauberer Separation of Concerns, Modernes React-Stack mit TypeScript für Typ-Sicherheit, Iterative Entwicklung mit wöchentlichen Reviews, Agile Priorisierung mit klarer Nutzer-Fokussierung, Design-System für schnelle Konsistenz.",
    "stats": [
      {
        "value": "+300%",
        "label": "mehr App-Installationen nach Launch"
      },
      {
        "value": "5 Sek",
        "label": "bis zum vollständigen Profilein Upload via NFC"
      },
      {
        "value": "+60%",
        "label": "Conversion bei Messegesprächsterminen"
      }
    ],
    "mockupImages": [
      "/uploads/cases/tap2link-mockup-1.png",
      "/uploads/cases/tap2link-hero.png",
      "/uploads/cases/tap2link-mockup-3.png"
    ]
  }
};

export function getCaseDetail(slug: string): CaseDetail | undefined {
  return caseDetailsMap[slug];
}
