// This file is auto-generated by scripts/generate-content.ts. Do not edit by hand.

export const siteData = {
  heroHeadline: "Wir bauen digitale Lösungen für dein Business.",
  heroSubline: "Ein kleines, fokussiertes Team aus Strategy, Design und Projektleitung entwickelt in wenigen Wochen digitale Produkte, die wirklich funktionieren.",
  heroCta: "Gespräch vereinbaren",
  heroCtaSecondary: "Projekte ansehen",
  clientLogosLabel: "Diese Kunden setzen auf uns",
  nav: [
  {
    "label": "Leistungen",
    "href": "/leistungen"
  },
  {
    "label": "Projekte",
    "href": "/#projekte"
  },
  {
    "label": "Pricing",
    "href": "/#pricing"
  },
  {
    "label": "Kontakt",
    "href": "/#kontakt"
  }
],
};
